export const confituras = [
  { productName: "ALFAJORCITOS BLANCOS", productQuantity: 0 },
  { productName: "ALFAJORCITOS NEGROS", productQuantity: 0 },
  { productName: "ALFAJORCITOS MAICENA", productQuantity: 0 },
  { productName: "ANILLITOS BLANCOS", productQuantity: 0 },
  { productName: "ANILLITOS NEGROS", productQuantity: 0 },
  { productName: "ANILLITOS DDL BLANCOS", productQuantity: 0 },
  { productName: "ANILLITOS DDL NEGROS", productQuantity: 0 },
  { productName: "CARIOCAS", productQuantity: 0 },
  { productName: "CUBANAS", productQuantity: 0 },
  { productName: "COOCKIES CHIPS", productQuantity: 0 },
  { productName: "COOCKIES ROCKLETS", productQuantity: 0 },
  { productName: "ANILLITOS DDL NEGROS", productQuantity: 0 },
  { productName: "COQUITOS", productQuantity: 0 },
  { productName: "COQUITOS DDL", productQuantity: 0 },
  { productName: "CONITOS BLANCOS", productQuantity: 0 },
  { productName: "CONITOS NEGROS", productQuantity: 0 },
  { productName: "HOJALDRE CON MEMBRILLO", productQuantity: 0 },
  { productName: "LENGÜITAS", productQuantity: 0 },
  { productName: "MASA SUIZA", productQuantity: 0 },
  { productName: "MASA SUIZA SIN AZUCAR", productQuantity: 0 },
  { productName: "MILHOJA MANZANA", productQuantity: 0 },
  { productName: "MILHOJAS BLANCA", productQuantity: 0 },
  { productName: "MILHOJAS NEGRA", productQuantity: 0 },
  { productName: "PALITOS ANIS", productQuantity: 0 },
  { productName: "PALITOS QUESO", productQuantity: 0 },
  { productName: "PALITOS QUESO AGRIDULCE", productQuantity: 0 },
  { productName: "PALMERITAS", productQuantity: 0 },
  { productName: "PALMERITAS RELLENAS", productQuantity: 0 },
  { productName: "PEPAS BATATA", productQuantity: 0 },
  { productName: "PEPAS DDL", productQuantity: 0 },
  { productName: "PEPAS MEMBRILLO", productQuantity: 0 },
  { productName: "POLVORONES FRUTILLA", productQuantity: 0 },
  { productName: "POLVORONES MARFILADOS", productQuantity: 0 },
  { productName: "REINAS", productQuantity: 0 },
  { productName: "ROSCA ALEMANA", productQuantity: 0 },
  { productName: "ROSQUITAS HUEVO", productQuantity: 0 },
  { productName: "SCONS", productQuantity: 0 },
  { productName: "SCONS CHIP", productQuantity: 0 },
  { productName: "SCONS FRUTA", productQuantity: 0 },
  { productName: "SCONS LIMON", productQuantity: 0 },
  { productName: "SCONS VAINILLA", productQuantity: 0 },
];

export const alfajores = [
  { productName: "ALFAJOR CHOCOLATE", productQuantity: 0 },
  { productName: "ALFAJOR BLANCO", productQuantity: 0 },
  { productName: "ALFAJOR MILHOJAS", productQuantity: 0 },
  { productName: "ALFAJOR MAICENA", productQuantity: 0 },
];

export const budines = [
  { productName: "BUDIN CHIPS", productQuantity: 0 },
  { productName: "BUDIN CHOCOLATE Y DDL", productQuantity: 0 },
  { productName: "BUDIN LIMON Y AMAPOLA", productQuantity: 0 },
  { productName: "BUDIN MARMOLADO", productQuantity: 0 },
  { productName: "BUDIN NARANJA", productQuantity: 0 },
  { productName: "BUDIN MANZANA", productQuantity: 0 },
];

export const pastafrolas = [
  { productName: "MEMBRILLO", productQuantity: 0 },
  { productName: "BATATA", productQuantity: 0 },
  { productName: "COMBINADA", productQuantity: 0 },
  { productName: "DULCE DE LECHE", productQuantity: 0 },
];

export const tartaDulces = [
  { productName: "RICOTA", productQuantity: 0 },
  { productName: "DURAZNO", productQuantity: 0 },
  { productName: "FRUTILLA", productQuantity: 0 },
  { productName: "COCO", productQuantity: 0 },
  { productName: "TOFFI", productQuantity: 0 },
  { productName: "KIWI", productQuantity: 0 },
  { productName: "MILHOJAS BLANCA", productQuantity: 0 },
  { productName: "MILHOJAS NEGRA", productQuantity: 0 },
];

export const tartaDulcesChicas = [
  { productName: "RICOTA", productQuantity: 0 },
  { productName: "DURAZNO", productQuantity: 0 },
  { productName: "FRUTILLA", productQuantity: 0 },
  { productName: "COCO", productQuantity: 0 },
  { productName: "TOFFI", productQuantity: 0 },
  { productName: "KIWI", productQuantity: 0 },
  { productName: "MILHOJAS BLANCA", productQuantity: 0 },
  { productName: "MILHOJAS NEGRA", productQuantity: 0 },
];

export const porciones = [
  { productName: "TARTA RICOTA", productQuantity: 0 },
  { productName: "TARTA COCO", productQuantity: 0 },
  { productName: "FROLA BATATA", productQuantity: 0 },
  { productName: "FROLA MEMBRILLO", productQuantity: 0 },
];

export const panificados = [
  { productName: "PEBETE X4", productQuantity: 0 },
  { productName: "ARABE X4", productQuantity: 0 },
  { productName: "FUGAZZITA", productQuantity: 0 },
  { productName: "PANCHOS X8", productQuantity: 0 },
  { productName: "PANCHOS X12", productQuantity: 0 },
  { productName: "SUPER PANCHOS X8", productQuantity: 0 },
  { productName: "SUPER PANCHOS X12", productQuantity: 0 },
  { productName: "HAMBURGUESA X4", productQuantity: 0 },
  { productName: "PAN DE MOLDE MAIZ", productQuantity: 0 },
  { productName: "PAN DE MOLDE SEMILLA", productQuantity: 0 },
  { productName: "PAN DE MOLDE BLANCO", productQuantity: 0 },
  { productName: "PAN DE MOLDE SALVADO", productQuantity: 0 },
  { productName: "PAN SABORIZADO x Kg", productQuantity: 0 },
];

export const galletas = [
  { productName: "ZAPATILLAS CON SAL", productQuantity: 0 },
  { productName: "ZAPATILLAS SIN SAL", productQuantity: 0 },
  { productName: "PLUMITAS", productQuantity: 0 },
  { productName: "CON SEMILLAS", productQuantity: 0 },
  { productName: "ABIZCOCHADAS", productQuantity: 0 },
  { productName: "TALITAS COMUNES CON SAL", productQuantity: 0 },
  { productName: "TALITAS COMUNES SIN SAL", productQuantity: 0 },
  { productName: "TALITAS QUESO", productQuantity: 0 },
  { productName: "TALITAS ROQUEFORT", productQuantity: 0 },
  { productName: "TALITAS PIZZA", productQuantity: 0 },
  { productName: "TALITAS CEBOLLA", productQuantity: 0 },
  { productName: "TALITAS JAMON", productQuantity: 0 },
  { productName: "TALITAS AJO", productQuantity: 0 },
  { productName: "TALITAS PROVENZAL", productQuantity: 0 },
  { productName: "GRISINES COMUNES C/SAL", productQuantity: 0 },
  { productName: "GRISINES COMUNES S/SAL", productQuantity: 0 },
  { productName: "GRISINES SALVADO", productQuantity: 0 },
  { productName: "GRISINES SEMILLAS", productQuantity: 0 },
];

export const comidas = [
  { productName: "SAN. MIGA J Y X4", productQuantity: 0 },
  { productName: "SAN. MIGA J Y X6", productQuantity: 0 },
  { productName: "SAN. MIGA SALAME Y QUESO", productQuantity: 0 },
  { productName: "SAN. MIGA ROQUE Y QUESO", productQuantity: 0 },
  { productName: "SAN. MIGA ROQUE Y JAMON", productQuantity: 0 },
  { productName: "SAN. MIGA CRUDO Y QUESO", productQuantity: 0 },
  { productName: "SAN. MIGA ZANAHORIA Y HUEVO", productQuantity: 0 },
  { productName: "SAN. MIGA MORRON Y HUEVO", productQuantity: 0 },
  { productName: "PREPIZZA", productQuantity: 0 },
  { productName: "PREPIZZA CEBOLLA", productQuantity: 0 },
  { productName: "PIZZETA", productQuantity: 0 },
  { productName: "PIZZETA CEBOLLA", productQuantity: 0 },
  { productName: "P. HORNEAR MUZZA", productQuantity: 0 },
  { productName: "P. HORNEAR ESPECIAL", productQuantity: 0 },
  { productName: "P. HORNEAR CUATRO QUESOS", productQuantity: 0 },
  { productName: "P. HORNEAR PRIMAVERA", productQuantity: 0 },
  { productName: "P. HORNEAR ROQUEFORT", productQuantity: 0 },
  { productName: "P. HORNEAR ASADA", productQuantity: 0 },
  { productName: "P. HORNEAR CALABRESA", productQuantity: 0 },
  { productName: "P. TARTA ACELGA", productQuantity: 0 },
  { productName: "TARTA JAMON Y QUESO", productQuantity: 0 },
  { productName: "TARTA ZAPALLITO", productQuantity: 0 },
  { productName: "TARTA POLLO", productQuantity: 0 },
  { productName: "TARTA CAPRESE", productQuantity: 0 },
  { productName: "TARTA DE CEBOLLA", productQuantity: 0 },
  { productName: "EMPANADA DE CARNE", productQuantity: 0 },
  { productName: "EMPANADA DE POLLO", productQuantity: 0 },
  { productName: "EMPANADA DE VERDURA", productQuantity: 0 },
  { productName: "FATAY", productQuantity: 0 },
];
